require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/transcript_courses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TranscriptCourse. As you add validations to TranscriptCourse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TranscriptCourse.create! valid_attributes
      get transcript_courses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      transcript_course = TranscriptCourse.create! valid_attributes
      get transcript_course_url(transcript_course)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_transcript_course_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      transcript_course = TranscriptCourse.create! valid_attributes
      get edit_transcript_course_url(transcript_course)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TranscriptCourse" do
        expect {
          post transcript_courses_url, params: { transcript_course: valid_attributes }
        }.to change(TranscriptCourse, :count).by(1)
      end

      it "redirects to the created transcript_course" do
        post transcript_courses_url, params: { transcript_course: valid_attributes }
        expect(response).to redirect_to(transcript_course_url(TranscriptCourse.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TranscriptCourse" do
        expect {
          post transcript_courses_url, params: { transcript_course: invalid_attributes }
        }.to change(TranscriptCourse, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post transcript_courses_url, params: { transcript_course: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested transcript_course" do
        transcript_course = TranscriptCourse.create! valid_attributes
        patch transcript_course_url(transcript_course), params: { transcript_course: new_attributes }
        transcript_course.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the transcript_course" do
        transcript_course = TranscriptCourse.create! valid_attributes
        patch transcript_course_url(transcript_course), params: { transcript_course: new_attributes }
        transcript_course.reload
        expect(response).to redirect_to(transcript_course_url(transcript_course))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        transcript_course = TranscriptCourse.create! valid_attributes
        patch transcript_course_url(transcript_course), params: { transcript_course: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested transcript_course" do
      transcript_course = TranscriptCourse.create! valid_attributes
      expect {
        delete transcript_course_url(transcript_course)
      }.to change(TranscriptCourse, :count).by(-1)
    end

    it "redirects to the transcript_courses list" do
      transcript_course = TranscriptCourse.create! valid_attributes
      delete transcript_course_url(transcript_course)
      expect(response).to redirect_to(transcript_courses_url)
    end
  end
end
